project_id = "ufinpydmvehncksexkpo"
[functions.judge0-execute]
enabled = true
verify_jwt = true
import_map = "./functions/judge0-execute/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/judge0-execute/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/judge0-execute/*.html" ]
